### ISSUE TITLE
Feature request: useAsciiArt()

### ISSUE THREAD

**Issue by rsodre** [samuelweckstrom/react-ascii-text#1]
This package is really cool! I love it!

**Feature request**: new hook `useAsciiArt()`
Instead of rendering text with the font, it will render the actual ASCII art we already have, taking care of the spaces and applying animations.

**Comment by samuelweckstrom** [comment]
Happy you like it!

It's a nice idea, could look into this. Are you using some tool to create ASCII art I could try out?

**Comment by rsodre** [comment]
Not me, but my team colleague does some by hand, like this one here:
[https://github.com/funDAOmental/endlessquest](https://github.com/funDAOmental/endlessquest)
With a package like yours, we can start bringing them to the apps ;)
